//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhinobyte.CodeAnalysis.NetAnalyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnalyzerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rhinobyte.CodeAnalysis.NetAnalyzers.AnalyzerResources", typeof(AnalyzerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type members should be ordered correcty into their respective groups..
        /// </summary>
        internal static string RBCS_0001_AnalyzerDescription {
            get {
                return ResourceManager.GetString("RBCS_0001_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not ordered correctly by group.
        /// </summary>
        internal static string RBCS_0001_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RBCS_0001_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type members should be ordered by group.
        /// </summary>
        internal static string RBCS_0001_AnalyzerTitle {
            get {
                return ResourceManager.GetString("RBCS_0001_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type members within the same group should be ordered correctly..
        /// </summary>
        internal static string RBCS_0002_AnalyzerDescription {
            get {
                return ResourceManager.GetString("RBCS_0002_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not ordered alphabetically or by configured priority.
        /// </summary>
        internal static string RBCS_0002_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RBCS_0002_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type members within the same group should be ordered correctly.
        /// </summary>
        internal static string RBCS_0002_AnalyzerTitle {
            get {
                return ResourceManager.GetString("RBCS_0002_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member assignments in the object initializer are not ordered correctly..
        /// </summary>
        internal static string RBCS_0003_AnalyzerDescription {
            get {
                return ResourceManager.GetString("RBCS_0003_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member assignments &apos;{0}&apos; are out of order.
        /// </summary>
        internal static string RBCS_0003_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RBCS_0003_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member assignments in an object initializer are ordered correctly.
        /// </summary>
        internal static string RBCS_0003_AnalyzerTitle {
            get {
                return ResourceManager.GetString("RBCS_0003_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our code fix provider can automatically alphabetize your enum member names. Use with caution..
        /// </summary>
        internal static string RBCS_0004_AnalyzerDescription {
            get {
                return ResourceManager.GetString("RBCS_0004_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order enum member names alphabetically (potentially breaking change).
        /// </summary>
        internal static string RBCS_0004_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RBCS_0004_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order enum members alphabetically.
        /// </summary>
        internal static string RBCS_0004_AnalyzerTitle {
            get {
                return ResourceManager.GetString("RBCS_0004_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order method parameters alphabetically..
        /// </summary>
        internal static string RBCS_0005_AnalyzerDescription {
            get {
                return ResourceManager.GetString("RBCS_0005_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order method parameters alphabetically.
        /// </summary>
        internal static string RBCS_0005_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RBCS_0005_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order method parameters alphabetically.
        /// </summary>
        internal static string RBCS_0005_AnalyzerTitle {
            get {
                return ResourceManager.GetString("RBCS_0005_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our code fix provider can automatically alphabetize your record type member names. Use with caution..
        /// </summary>
        internal static string RBCS_0006_AnalyzerDescription {
            get {
                return ResourceManager.GetString("RBCS_0006_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order record type member names alphabetically (potentially breaking change).
        /// </summary>
        internal static string RBCS_0006_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RBCS_0006_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order record type members alphabetically.
        /// </summary>
        internal static string RBCS_0006_AnalyzerTitle {
            get {
                return ResourceManager.GetString("RBCS_0006_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using explicitly named optional parameters can help with code maintainability and help guard against errors and unintended behavior changes..
        /// </summary>
        internal static string RBCS_0010_AnalyzerDescription {
            get {
                return ResourceManager.GetString("RBCS_0010_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional parameter &apos;{0}&apos; should be passed explicitly using it&apos;s name.
        /// </summary>
        internal static string RBCS_0010_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RBCS_0010_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use explicitly named optional parameters.
        /// </summary>
        internal static string RBCS_0010_AnalyzerTitle {
            get {
                return ResourceManager.GetString("RBCS_0010_AnalyzerTitle", resourceCulture);
            }
        }
    }
}
